### ISSUE TITLE
请问使用自己数据加入数据库的字典格式

### ISSUE THREAD

**Issue by Polaris-L** [L-codes/pwcrack-framework#10]
想问一下在words.txt中新增如下图所示的对应关系如何操作
<img width="334" alt="image" src="https://user-images.githubusercontent.com/39089928/181693839-cd4d44f5-82e6-466f-b625-ef505cd26b54.png">

又或者这样的字典只能通过my_dict.txt添加？那么应该是怎样的格式？比如md5:明文还是md5空格+明文

**Comment by L-codes** [comment]
目前仅支持在`word.txt`上添加

**Comment by L-codes** [comment]
只支持明文，你hash放进去的话你解密得到你的 Hash? cmd5等接口支持salt的 无需指定salt

**Comment by Polaris-L** [comment]
我只添加明文的话，hash放进去对应不到本地数据库的明文，只会显示cmd5存在付费内容

**Comment by L-codes** [comment]
你放明文 init之后 就会匹配到 hash

**Comment by Polaris-L** [comment]
尝试的结果如下：
<img width="640" alt="image" src="https://user-images.githubusercontent.com/39089928/181712913-f87255a4-84d4-44b8-be78-5f5d90152859.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/39089928/181713197-cd46db61-3b23-4210-989b-923b3e96a14f.png">

**Comment by L-codes** [comment]
`./pwcrack init`了吗？才会去更新库

**Comment by Polaris-L** [comment]
更新库是./pwcrack updatedb吧，initdb一开始就建了，我导入的普通md5加密的数据就可以正常搜索到，上面那种格式就不行。
<img width="634" alt="image" src="https://user-images.githubusercontent.com/39089928/181716795-6593e018-52df-432f-ae1b-63b03ff8292e.png">

**Comment by L-codes** [comment]
`init`也行，速度没有 `updatedb` 快，我怕你第一次使用

**Comment by L-codes** [comment]
你说不行的格式是？

**Comment by Polaris-L** [comment]
我再次使用init出现这个报错：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/39089928/181719695-0bf5df2b-3432-4a85-affe-70e63cb7bc1e.png">
d31cc5adf4127074cfde952c1ab3263a:02ccfb
qxb123456
这种格式不行

**Comment by L-codes** [comment]
对的 不能带salt

**Comment by Polaris-L** [comment]
好嘞
