### ISSUE TITLE
initdb错误：Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#14]
/home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:90:in `encode': U+7A7A from UTF-8 to ISO-8859-1 (Encoding::UndefinedConversionError)

/home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:90:in `encode': U+7A7A from UTF-8 to ISO-8859-1 (Encoding::UndefinedConversionError)
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:90:in `block (2 levels) in initdb'
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:56:in `each'
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:56:in `block in initdb'
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:43:in `each'
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:43:in `each_with_index'
	from /home/test/pwcrack-framework/lib/cli_cmd/initdb.rb:43:in `initdb'
	from /home/test/pwcrack-framework/lib/cli.rb:82:in `get_input'
	from /home/test/pwcrack-framework/lib/cli.rb:61:in `commandline!'
	from ./pwcrack:24:in `<main>'

# uname -a
Linux centos 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by L-codes** [comment]
你的 words.txt 是添加了什么中文之类的字典吗？

**Comment by winezer0** [comment]
用的内置的字典呀

**Comment by Hi-Mike** [comment]
533162确实有包含中文,删了就可以

**Comment by L-codes** [comment]
嗯 已删除这个中文的了
