### ISSUE TITLE
建议添加几个sha1和md5的组合算法离线库生成

### ISSUE THREAD

**Issue by moyuwa** [L-codes/pwcrack-framework#15]
基于www.cmd5.com筛选，去除加盐的，可以再加入mysql5、sha1(sha1($psss))、sha1(md5($psss))、md5(sha1($psss))几个算法到离线库生成

**Comment by L-codes** [comment]
这个建议保留，后续考虑加入

**Comment by L-codes** [comment]
后面想了一下 还有 hex 和 bytes 的区别，sha1(sha1($psss))、sha1(md5($psss))、md5(sha1($psss)) 等场景遇到情况不够多，能否举一些实际应用数据库密码采用这些的算法的场景？

mysql5 就是 :mysql 的算法 已经包含了

**Comment by moyuwa** [comment]
使用场景确实不多，一般都是单算法
