### ISSUE TITLE
windows下报错

### ISSUE THREAD

**Issue by GYLQ** [L-codes/pwcrack-framework#19]
![image](https://user-images.githubusercontent.com/15842234/184935175-16e0431f-4828-4609-97d3-0396f2a8840c.png)

版本

![image](https://user-images.githubusercontent.com/15842234/184935223-dee3912f-43fd-48c9-9592-142ce90a2749.png)

**Comment by L-codes** [comment]
先运行 `bundle install` 安装依赖

**Comment by GYLQ** [comment]
![image](https://user-images.githubusercontent.com/15842234/185026051-22f4fa82-3d26-4751-9f29-9f2ad9d15800.png)

**Comment by GYLQ** [comment]
> 先运行 `bundle install` 安装依赖

师傅，我之前就这样运行下来的

版本3.1.1

**Comment by GYLQ** [comment]
方便联系一下微信嘛

**Comment by GYLQ** [comment]
OK了，换linux 就可以
![image](https://user-images.githubusercontent.com/15842234/185027789-e00c5990-434d-4746-92f4-196b5a1c22b7.png)

**Comment by L-codes** [comment]
> 方便联系一下微信嘛

你微信发我 我加你 至于这个我后续windows测试一下
