### ISSUE TITLE
可以支持批量吗，指定txt文件，指定加密方式

### ISSUE THREAD

**Issue by dagaoya** [L-codes/pwcrack-framework#2]
如题

**Comment by L-codes** [comment]
暂时不计划支持批量，因为很多是调用在线查询的，频率过高不好，批量建议还是去网站批量查询功能；
$ pwcrack banner -v # 可以查看目前支持的在线插件的网址。
README.md的Examples2/3有指定算法的示例，如指定md5: pwcrack <hash> md5.
