### ISSUE TITLE
查询接口

### ISSUE THREAD

**Issue by DongHuangT1** [L-codes/pwcrack-framework#20]
https://hashtoolkit.com/decrypt-hash/?hash=***
https://api.allinone.tools/encryption/decrypt/md5/***
https://api.allinone.tools/encryption/decrypt/sha1/***
https://api.allinone.tools/encryption/decrypt/sha256/***
https://api.allinone.tools/encryption/decrypt/sha384/***
https://api.allinone.tools/encryption/decrypt/sha512/***

**Comment by L-codes** [comment]
https://hashtoolkit.com 之前已经添加过 [plugin](https://github.com/L-codes/pwcrack-framework/blob/master/plugins/disable/hashtoolkit.rb) 无法正常使用
[https://api.allinone.tools](https://api.allinone.tools/encryption/decrypt/sha1/) 刚已经添加 插件 allinone

**Comment by DongHuangT1** [comment]
hashtoolkit和代码里稍微不一样.
旧: http://hashtoolkit.com/reverse-hash?hash=
新: https://hashtoolkit.com/decrypt-hash/?hash=

**Comment by L-codes** [comment]
可是我测试了 https://hashtoolkit.com/decrypt-hash/?hash=e10adc3949ba59abbe56e057f20f883e 响应 403

**Comment by DongHuangT1** [comment]
好像需要代理才可以...
![image](https://user-images.githubusercontent.com/51707652/186929713-17b6c6f0-6356-4d0f-b76e-6d174ea89012.png)
![image](https://user-images.githubusercontent.com/51707652/186930341-c0105ef3-fcba-4a07-930d-b93b4f7f8aac.png)

**Comment by L-codes** [comment]
确实需要翻墙，才能正常使用，不过我后面还是加上吧

**Comment by L-codes** [comment]
感谢提交 :)

**Comment by DongHuangT1** [comment]
感谢😘
