### ISSUE TITLE
M1没法用，在bundle install时提示`Bundle complete! 7 Gemfile dependencies, 28 gems now installed.`

### ISSUE THREAD

**Issue by NaliangzzZ** [L-codes/pwcrack-framework#22]
M1没法用，在bundle install时提示`Bundle complete! 7 Gemfile dependencies, 28 gems now installed.`

**Comment by L-codes** [comment]
这不是报错信息，请提供详细的报错信息

**Comment by NaliangzzZ** [comment]
`/Users/aaa/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:186:in `block in find_hash_type': undefined local variable or method `_1' for CLI:Module (NameError)
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:186:in `each_char'
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:186:in `each'
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:186:in `filter'
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:186:in `find_hash_type'
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/passwd.rb:37:in `passwd_analysis'
	from /Users/naliang/Downloads/CyberSpace_Security/Tools/pwcrack-framework/lib/cli.rb:62:in `commandline!'
	from ./pwcrack:24:in `<main>'
`

**Comment by L-codes** [comment]
你这个是ruby的版本太低了 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/20529064/205562745-be0e9c4c-792e-4983-8267-6c3260145125.png">
