### ISSUE TITLE
rjb 的安装问题，未设置 JAVA_HOME 报错`can't create Java VM (RuntimeError)`

### ISSUE THREAD

**Issue by loobug** [L-codes/pwcrack-framework#25]
java版本是否有要求

**Comment by L-codes** [comment]
目前看 jdk >= 5 的都可以，低版本的没有实测过，也许不行

**Comment by loobug** [comment]
为什么报这个错：pwcrack-framework/external/java_ext/java_ext.rb:13:in `add_jar': can't create Java VM (RuntimeError)

**Comment by L-codes** [comment]
应该是你的 JAVA_HOME没有设置好，建议设置好 JAVA_HOME后，重新安装 rjb
```python
gem uninstall rjb; export JAVA_HOME=XXXXXXXX; gem install rjb
```

**Comment by loobug** [comment]
重新卸载ruby，bundle install 安装报这个，报错
![image](https://user-images.githubusercontent.com/39818081/220493571-7accaae4-e2d8-497a-9c7d-3bea3034b4cb.png)
![image](https://user-images.githubusercontent.com/39818081/220494978-21eee394-3953-4f32-aa3c-a0c31b50067c.png)

![image](https://user-images.githubusercontent.com/39818081/220493211-a3fc798b-896a-4afe-9444-a58bc78d44b2.png)
![image](https://user-images.githubusercontent.com/39818081/220493266-3eaef252-89a4-4aa4-ac8b-515185044ccf.png)

**Comment by L-codes** [comment]
喔 你的环境是 Windows，那你则可以用下面命令，指定java的安装目录，这样就能顺利安装安装 `rjb` 库
一般路径为 `C:\Program Files\Java\jdkXXXX` ，记得重新启动 cmd.exe，才能生效，然后继续 `bundle install`
```ruby
setx JAVA_HOME "C://XXXXXX"
```

**Comment by L-codes** [comment]
我在 Windows 环境下测试了，问题已修复，更新  [v1.17.1](https://github.com/L-codes/pwcrack-framework/releases/tag/1.17.1) 版本进行使用
