### ISSUE TITLE
bundle install failed

### ISSUE THREAD

**Issue by loobug** [L-codes/pwcrack-framework#26]
bundle install 总是失败，windows  linux都试了 ，java1.8 java19 都试了，总是失败 不知道为啥
![image](https://user-images.githubusercontent.com/39818081/221100426-10840a78-20f2-4b63-b888-4153f797f91d.png)

![image](https://user-images.githubusercontent.com/39818081/221100394-5c24349c-9779-4e5c-b6cc-da6ec97fd2be.png)

**Comment by L-codes** [comment]
安装的是 v1.17.1版本吗？

**Comment by loobug** [comment]
是的 最新版本的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月24日 22:09
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [L-codes/pwcrack-framework] bundle install failed (Issue #26)


安装的是 v1.17.1版本吗？

―

**Comment by L-codes** [comment]
`echo $JAVA_HOME` 看看是有配置的吗？

**Comment by loobug** [comment]
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月25日 9:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [L-codes/pwcrack-framework] bundle install failed (Issue #26)


echo $JAVA_HOME 看看是有配置的吗？

―

**Comment by loobug** [comment]
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月25日 9:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [L-codes/pwcrack-framework] bundle install failed (Issue #26)


echo $JAVA_HOME 看看是有配置的吗？

―

**Comment by L-codes** [comment]
是windowsd 的话，用下面的命令看看
```bash
echo %JAVA_HOME%
```

**Comment by loobug** [comment]
![image](https://user-images.githubusercontent.com/39818081/223306699-e25b13f2-58b3-43ec-a8c5-04ac3231d819.png)
![image](https://user-images.githubusercontent.com/39818081/223306743-1b7b5b10-7ede-4f3d-9eda-6173f66c2494.png)
linux安装  ruby3.1 jdk17
![image](https://user-images.githubusercontent.com/39818081/223306800-fa50371a-9252-444d-a7a9-6b29b7097fe9.png)
![image](https://user-images.githubusercontent.com/39818081/223306854-4d5cf2d5-7b3f-499a-8e88-7fb58144bbbd.png)

**Comment by L-codes** [comment]
你尝试先安装 ruby-dev等编译环境，你的ruby是什么方式安装的？
 `apt install ruby-dev clang make libffi-dev`

**Comment by loobug** [comment]
GOOD, 安装以后bundle  install 正常，出现了新报错
![image](https://user-images.githubusercontent.com/39818081/223309619-f813a02a-22b0-47ba-b69a-fc42158c5ea1.png)

**Comment by L-codes** [comment]
你可以使用 `ruby pwcrack` 解决这个问题，跟魔术头有关

**Comment by loobug** [comment]
嗯嗯 可以

**Comment by loobug** [comment]
thank you very much!

**Comment by L-codes** [comment]
> GOOD, 安装以后bundle install 正常，出现了新报错
> ![image](https://user-images.githubusercontent.com/39818081/223309619-f813a02a-22b0-47ba-b69a-fc42158c5ea1.png)

这个 bug 我刚也修复了 https://github.com/L-codes/pwcrack-framework/commit/e824657f47c2abb083f649aa8cbdd1a1146c6701

你可以下最新的代码，依旧可以 `./pwcrack banner` 运行了

**Comment by loobug** [comment]
GOOD, IT IS VERY NICE.
![image](https://user-images.githubusercontent.com/39818081/223312657-ce9c6dd5-4e09-4107-9d99-69ab014468d5.png)
