### ISSUE TITLE
可否添加nacos密码破解

### ISSUE THREAD

**Issue by moyuwa** [L-codes/pwcrack-framework#27]

**Comment by L-codes** [comment]
nacos 是bcrypt 你有能解密的网站或者特别的思路吗？

**Comment by moyuwa** [comment]
依旧是密文哈希碰撞方式，没有其他的

**Comment by L-codes** [comment]
那如果是没有能在线查找碰撞的网站提供，这个暂时还是交给Hashcat要好，如果有更好办法再重新打开这个issue吧 ：）

**Comment by YshGitHubfcasd** [comment]
本地环境配置的文件，有nacos的账号和密码加密的，有什么方案能在spring启动的时候就加个解密操作，导致时密文的nacos客户端一启动就报错
