### ISSUE TITLE
希望 添加常见加密算法 本地数据库支持

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#29]
md5(md5($pass))    cs12345A   42cbd4e0f4840a73c6329f43c5061ae8  【目前解密不出来】
 sha256   123456    8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92  【目前解密不出来】

**Comment by L-codes** [comment]
这些好几个在线网站接口都支持的，也比较少见，不建议加入，会增大本地存储
