### ISSUE TITLE
[!] Partially dependent java plugins cannot be used normally

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#30]
运行时提示：
[!] Partially dependent java plugins cannot be used normally

是我没有安装插件吗，还是因为目前rjb不可用

**Comment by L-codes** [comment]
是jar的加载出问题了，你的rjb 应该运行没问题，可以提供一下系统版本和ruby版本吗？我有空测测

**Comment by L-codes** [comment]
windows什么版本？

**Comment by winezer0** [comment]
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎7/‎16
操作系统内部版本	19044.2965
体验	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by winezer0** [comment]
另外发现昨天那个md5(md5(string)) 格式的加密是支持的, 是在add后发现没有update localdb导致的

**Comment by L-codes** [comment]
md5(md5()) 是支持的 sha1(sha1()) 目前没有支持；plugins/disable 是已经用不了的在线插件

**Comment by winezer0** [comment]
好的，了解
