### ISSUE TITLE
导入字典是出现特殊字符导致程序崩溃，不知是否可以采用跳过的方式继续导入

### ISSUE THREAD

**Issue by k3vi-07** [L-codes/pwcrack-framework#31]
pwcrack updatedb
[*] Start update the local DB...

[*] Add record: 4794350

/Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:81:in `encode': "\xA7" on UTF-8 (Encoding::InvalidByteSequenceError)
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:81:in `block (2 levels) in updatedb'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:73:in `each'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:73:in `block in updatedb'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:59:in `each'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:59:in `each_with_index'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli_cmd/updatedb.rb:59:in `updatedb'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli.rb:84:in `get_input'
	from /Users/admin/Tools/other_tool/pwcrack-framework/lib/cli.rb:61:in `commandline!'
	from /Users/admin/Tools/other_tool/pwcrack-framework/pwcrack:24:in `<main>'

**Comment by L-codes** [comment]
已修复该问题，可以更新到 `1.17.2` 版本测试一下，如未解决重新打开该issue
