### ISSUE TITLE
【重大喜讯】解决windows下rjb无法使用问题

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#32]
我看这个插件带代码是通过rjb实现的，我不知道我的环境是否可以运行。

能提供一个finalshell加密密文和使用方法用于测试吗？

我的启动pwcrack时，会警告rjb的一些bug，这个以前提过。

**Comment by L-codes** [comment]
试试这个
`pwcrack base64:OGNqLj1Le11Br3AIelAiPaDJpfhBzmEN finalshell`

**Comment by winezer0** [comment]
我更新版本的时候，没有更新data下的字典，这个有影响吗

**Comment by L-codes** [comment]
没影响

**Comment by L-codes** [comment]
> artially dependent java plugins cannot be used normally

你的 java 环境有问题

**Comment by winezer0** [comment]
> > artially dependent java plugins cannot be used normally
> 
> 你的 java 环境有问题

感觉是有问题，以前也提过，但是一直没有成功解决。

**Comment by L-codes** [comment]
你是安装rjb成功的了，可尝试去 https://github.com/arton/rjb 提交issue 看看

> λ pwcrack base64:OGNqLj1Le11Br3AIelAiPaDJpfhBzmEN finalshell [!] Partially dependent java plugins cannot be used normally [*] Hash: 38636a2e3d4b7b5d41af70087a50223da0c9a5f841ce610d [+] Cipher Algorithm: FINALSHELL
> 
> ```
> No password found
> ```
> 
> [+] PWCrack (0/1) in 0.00 seconds.
> 
> 失败了

**Comment by winezer0** [comment]
提BUG了

https://github.com/arton/rjb/issues/95

**Comment by winezer0** [comment]
大佬你在windows下能正常使用吗？

**Comment by L-codes** [comment]
我测了一下 我windows跟你一样的问题。。。 linux和mac都正常

**Comment by winezer0** [comment]
> 我测了一下 我windows跟你一样的问题。。。 linux和mac都正常。待我有空跟进一下这个问题
感谢感谢

**Comment by winezer0** [comment]
在windows下主要由多种情况构成：

1、rjb 插件安装不成功 （基本都是 javah -version 命令中文乱码导致的），这个可以通过修改rjb的源码，重新编译通过，

2、rjb插件无法创建JVM虚拟机，这个好像在windows下解决不了，暂时放弃解决，建议大家不要使用windows使用rjb

**Comment by winezer0** [comment]
向rjb官方提的rjb无法运行问题 今天 已经修复!!! 

虽然还没有发布最终的gem文件，但是已经可以通过 自己编译安装gem文件实现 pwcrack在windows下正常运行

![image](https://github.com/L-codes/pwcrack-framework/assets/46115146/b5e82753-0863-4dfc-8039-fad57f4085f6)


具体修复代码可以查看 
arton/rjb at fix_95
https://github.com/arton/rjb/tree/fix_95

以下是编译好的 rjb-1.7.2-x64-mingw-ucrt.gem
[rjb-fix_95.zip](https://github.com/L-codes/pwcrack-framework/files/15105135/rjb-fix_95.zip)

使用方式：
```
gem install  rjb-1.7.2-x64-mingw-ucrt.gem
删除pwcacrak目录下的 Gemfile.lock 文件，重新运行 bundle install

```

**Comment by winezer0** [comment]
关闭问题，@L-codes 可以弄一个readme或者说明

**Comment by L-codes** [comment]
> 关闭问题，@L-codes 可以弄一个readme或者说明

等待rjb release 这边更新 Gemfile 就好了
