### ISSUE TITLE
initdb

### ISSUE THREAD

**Issue by 0nion1** [L-codes/pwcrack-framework#33]
Digest initialization failed: initialization error (OpenSSL::Digest::DigestError)

**Comment by 0nion1** [comment]
<img width="1108" alt="image" src="https://github.com/L-codes/pwcrack-framework/assets/53221874/43d98bea-605c-4471-9386-7fe9c05b120f">

**Comment by L-codes** [comment]
这个问题是因为 openssl > 3.0 版本，已经不支持 md4 des 等不安全hash和加密算法了，需要你自行降低 ruby编译时 openssl 的版本

**Comment by li-baige** [comment]
我的报错是这样的：
<img width="1080" alt="截屏2023-08-18 23 50 55" src="https://github.com/L-codes/pwcrack-framework/assets/76275424/187a1d7b-548e-4880-aaba-016ebe42f208">

**Comment by L-codes** [comment]
@li-baige  你是不是打开过 data/words.txt 然后保存了？

**Comment by li-baige** [comment]
确实是这样，顺便提个小建议，就是有时候cmd5会提示该条数据是个付费记录，需要购买，使用工具的时候，如果是这样的情况会无结果，建议这边可以打印一下需要付费的提示比如cmd5的提示，当人如果接口不返回这个字短的话，就算了。

**Comment by L-codes** [comment]
@li-baige  pwcrack add word 可以添加，如果多的话，建议PR到本项目。然后你的建议本身就有这样的提醒了，会以标黄提醒：
<img width="709" alt="image" src="https://github.com/L-codes/pwcrack-framework/assets/20529064/bbcf5d74-2b76-4da8-8ba2-13457ce2ed16">
