### ISSUE TITLE
遇到收费的解密项目，但是又有点不一样

### ISSUE THREAD

**Issue by blzh1** [L-codes/pwcrack-framework#35]
( 2.98s)          nitrxgen: system:dss:Admin123
[*] ( 7.37s)          cmd5: Found, but this is a payment record.
[*] ( 7.50s)        cmd5en: Found, but this is a payment record.

nitrxgen: system:dss:Admin123（这是解出来三个密码？）

**Comment by L-codes** [comment]
你hash可以可以发一下吗？或者你复制全一点

**Comment by blzh1** [comment]
![image](https://github.com/L-codes/pwcrack-framework/assets/119399614/1d8f1ebf-6f4b-4478-bb4a-fec361c828d5)

**Comment by blzh1** [comment]
我有两个密文是这种情况

**Comment by L-codes** [comment]
没错的 system:dss:Admin123 的md5就是`1ebe47fb5b1299c1ecc061e248450b83`

**Comment by blzh1** [comment]
所以确实是三个密码？还是说 'system:dss:Admin123'这个字符串就是密码

**Comment by L-codes** [comment]
'system:dss:Admin123'这个字符串就是密码

**Comment by blzh1** [comment]
谢谢
