### ISSUE TITLE
mysql8 Caching_sha2_password 算法支持吗？

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#38]
mysql8 Caching_sha2_password 算法支持吗？

mysql是不是指的 mysql_native_password  算法

**Comment by L-codes** [comment]
暂未支持，Caching_sha2_password 我后续研究一下

**Comment by L-codes** [comment]
我看了一下 新的认证方式 存储到数据库的 hash 没办法建立彩虹表等方式查询了 [参考](https://blog.csdn.net/song854601134/article/details/130942178)
