### ISSUE TITLE
【功能建议】希望能增加插件的批量调用功能

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#39]
希望能增加插件的批量调用功能

输入多个hash，然后本地调用识别，输出 hash 和明文 

主要是为了解析一下高频hash，便于制作高频口令字典。

**Comment by L-codes** [comment]
localdb 可以自行添加你认为的高频字典加入，查询一些常见的hash ，至于批量查询这个没有实现的原因是部分在线插件，请求频率高就无法正常工作的了，你看有什么好的建议？

**Comment by winezer0** [comment]
我的需求是 在调用 localdb  等本地数据库的时候支持批量处理就行。

批量功能还是很有必要的，默认用户也不会主动批量调用联网查询的插件。

改造方案的话，

1、输出的时候 带上原始加密字符串 hash方法  解密结果

2、输入增加 文件读取功能（可以添加参数或者用file:表示），遍历调用函数

感谢，比较有需求

**Comment by L-codes** [comment]
1、2需求都是针对localdb吗? 如果是，我的建议是自己构建一个彩虹表查询，效率和效果都要比pwcrack要好，定位是为了方便对密文进行分析和尝试解密而已

**Comment by winezer0** [comment]
是的，但是这个用的习惯一些，只要能解密常见的就行了，

**Comment by winezer0** [comment]
放弃 自己改了一个-q 情况下的输出，输出了hash和明文，批量功能如果有需要的话再加吧
