### ISSUE TITLE
關於dmd5

### ISSUE THREAD

**Issue by 687766616e** [L-codes/pwcrack-framework#4]
http://www.dmd5.com ==> https://www.zuwuwang.com/ ???

https://fofa.so/result?q=title%3D%3D%22md5%E8%A7%A3%E5%AF%86+www.dmd5.com%22&qbase64=dGl0bGU9PSJtZDXop6Plr4Ygd3d3LmRtZDUuY29tIg%3D%3D&full=true

**Comment by huitc** [comment]
https://fofa.so/result?q=%22jiejia%22+%26%26+%28+%22post%22+%7C%7C+%22get%22+%29+%26%26+%22jie%22&qbase64=ImppZWppYSIgJiYgKCAicG9zdCIgfHwgImdldCIgKSAmJiAiamllIg%3D%3D&full=true

www.cmd5.la ?????????????

**Comment by L-codes** [comment]
www.zuwuwang.com 查询的结果到 cmd5.la 在cmd5la.rb 插件中已经包含
