### ISSUE TITLE
关于windows  无法重新加载 JVM 的问题

### ISSUE THREAD

**Issue by winezer0** [L-codes/pwcrack-framework#40]
发现代码里面有一句

# ref: https://github.com/arton/rjb/issues/34

puts '[!] Partially dependent java plugins cannot be used normally'

我重新在windows中编译了rjb，但是 windows中还是会提示  can't create Java VM (RuntimeError)  

这个bug能解决吗

**Comment by winezer0** [comment]
目前这应该是最后一个问题了，解决了这个问题就能够windows使用rjb了

**Comment by L-codes** [comment]
确实是有这个问题 暂时没有解决 https://github.com/arton/rjb/issues/34

**Comment by winezer0** [comment]
有没有其他的模块，调用java代码，或者改成system调用输出

**Comment by L-codes** [comment]
暂时没有发现其它比价好的调用java的，改用system jar 调用的话太不优雅了，而且目前依赖java的只有两个模块；而且现在正在研发一个c/s架构的系统，不需要客户端有java等的依赖安装，敬请期待

**Comment by winezer0** [comment]
JRuby 开发怎么样
https://github.com/jruby/jruby

**Comment by L-codes** [comment]
为了两个插件转用 jruby。。。还不如让rjb解决这个问题。不过也乐于接受 jruby版本的贡献PR，或者另起一个branch

**Comment by winezer0** [comment]
刚收到rjb issue的回复， 看看能不能解决吧，不能解决再说咯，ruby我只是业余的，jruby是一点不会
