### ISSUE TITLE
请问是使用的hash碰撞吗？

### ISSUE THREAD

**Issue by jingyuexing** [L-codes/pwcrack-framework#8]
有好多摘要算法都已经有hash碰撞算法了 比如

* MD4
* RIPEMD
* MD5
* SHA-1

相关的论文有:
- [https://eprint.iacr.org/2004/199.pdf](https://eprint.iacr.org/2004/199.pdf)
- [http://people.csail.mit.edu/yiqun/SHA1AttackProceedingVersion.pdf](http://people.csail.mit.edu/yiqun/SHA1AttackProceedingVersion.pdf)
- [How to Break MD5 and Other Hash Functions](https://www.iacr.org/cryptodb/archive/2005/EUROCRYPT/2868/2868.pdf)

**Comment by L-codes** [comment]
目前不是使用hash碰撞的。
该框架目前hash的破解只是通过在线网站查询和离线hash表查询的方式尝试破解，非hash的密文就尝试直接解密。
hash碰撞这个技术暂时想不到可以怎么利用 (我理解的hash碰撞是两个不同的数据计算出一样的hash值)

**Comment by jingyuexing** [comment]
> 目前不是使用hash碰撞的。 该框架目前hash的破解只是通过在线网站查询和离线hash表查询的方式尝试破解，非hash的密文就尝试直接解密。 hash碰撞这个技术暂时想不到可以怎么利用 (我理解的hash碰撞是两个不同的数据计算出一样的hash值)

我记得有个hash碰撞的例子 王小云 教授写的源码

**Comment by L-codes** [comment]
hash碰撞效果是怎样的？怎么运用到密码恢复中？

**Comment by jingyuexing** [comment]
> hash碰撞效果是怎样的？怎么运用到密码恢复中？

[hashclash](https://github.com/cr-marcstevens/hashclash)

**Comment by L-codes** [comment]
好的 我去了解一下

**Comment by L-codes** [comment]
> > hash碰撞效果是怎样的？怎么运用到密码恢复中？
> 
> [hashclash](https://github.com/cr-marcstevens/hashclash)

这个项目就是我理解的正常hash碰撞，两个不同的数据，通过碰撞在追加数据，计算出一样的hash值，这个技术怎么运用到密码恢复中？

**Comment by jingyuexing** [comment]
> > > hash碰撞效果是怎样的？怎么运用到密码恢复中？
> > 
> > 
> > [hashclash](https://github.com/cr-marcstevens/hashclash)
> 
> 这个项目就是我理解的正常hash碰撞，两个不同的数据，通过碰撞在追加数据，计算出一样的hash值，这个技术怎么运用到密码恢复中？

其实我只有一个很模糊的想法,但是 ……………… 总感觉有问题

**Comment by L-codes** [comment]
嗯 反正这个技术我是没想到怎么在框架中利用，先关闭该 Issue，后续有需要我再打开
