### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zhiao6** [L-codes/pwcrack-framework#9]
运行报错是什么原因呢？怎么处理
![image](https://user-images.githubusercontent.com/74243945/181675482-46a9c34c-f0d6-4eb4-bd96-742452d6f810.png)

**Comment by Polaris-L** [comment]
同样的问题，疑似mac安装bundle版本较低，但是又更新不了/usr/bin下的bundle

**Comment by L-codes** [comment]
ruby的版本过低，要用ruby 3.0以上

**Comment by zhiao6** [comment]
> ruby的版本过低用，ruby 3.0以上

好的，已解决
